
kind: Job
apiVersion: batch/v1
metadata:
  name: gnn
spec:
  template:
    spec:
      hostIPC: true
      containers:
      - name: icenetgnn
        image: "laueb4818/icenet2:latest"
        workingDir: /storage/icenet2/
        command: ["/bin/bash", "-c"]
        args: ["source activate icenet && 
        icenet_dataset_create test_data_1990_2020 north -l 1 -fd 7 -ob 2 -w 4"]
        stdin: true
        tty: true
        env:
        - name: WANDB_API_KEY
          valueFrom:
            secretKeyRef:
              name: wandb
              key: apikey
        volumeMounts:
        - name: storage
          mountPath: /storage
        # - name: .cdsapirc
        #   mountPath: ~/.cdsapirc
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: storage
      # - name: .cdsapirc
      #   persistentVolumeClaim:
      #     claimName: .cdsapirc
      restartPolicy: OnFailure
  backoffLimit: 0